In [2]:
import pandas as pd
import numpy as np

### Problem 1

In [3]:
pd.__version__

'2.3.1'

In [4]:
df = pd.read_csv('car_fuel_efficiency.csv')
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

### Problem 2

In [6]:
df.shape[0]

9704

### Problem 3

In [7]:
df.fuel_type.nunique()

2

### Problem 4

In [9]:
(df.isnull().sum() > 0).sum()

np.int64(4)

### Problem 5

In [13]:
df.query('origin == "Asia"').fuel_efficiency_mpg.max()

np.float64(23.759122836520497)

### Problem 6

In [22]:
median = df.horsepower.median()
median

np.float64(149.0)

In [23]:
mode = df.horsepower.value_counts(sort=True,ascending=False).values[0]

In [24]:
df['horsepower_filled'] = df.horsepower.fillna(value=mode)
df.horsepower_filled.median()

np.float64(146.0)

### Problem 7

In [30]:
X = df.loc[df.origin=='Asia', ['vehicle_weight', 'model_year']].head(7).values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [29]:
X.T

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [31]:
XTX = X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [32]:
XTX_inv = np.linalg.inv(XTX)

In [38]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]

XTX_inv.dot(X.T).dot(y).sum()

np.float64(0.5187709081074016)